spring:
  application:
    name: travel-booking-app

amadeus:
  base-url: ${AMADEUS_BASE_URL:https://test.api.amadeus.com}
  client-id: ${AMADEUS_CLIENT_ID:}
  client-secret: ${AMADEUS_CLIENT_SECRET}

car-api:
  base-url: ${CAR_API_BASE_URL:https://priceline-com-provider.p.rapidapi.com}
  key: ${CAR_API_KEY}
  host: ${CAR_API_HOST}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000